### ISSUE TITLE
Support For board state to Image 

### ISSUE THREAD

**Issue by jalpp** [bhlangonijr/chesslib#101]
It be nice if the lib supports image generation based on board state printing out the board state is good for logging but sharing a chess board in image format is more useful 

Thanks

**Comment by Oziomajnr** [comment]
Might be a big ask from a chess library, but I implemented something similar for android here https://github.com/Oziomajnr/PgnToGif/blob/main/app/src/main/java/com/chunkymonkey/pgntogifconverter/converter/ChessBoardToBitmapConverter.kt
it converts a board state to Bitmap, the implementation can be adapted to suit your need.
