### ISSUE TITLE
Legal Move list not complete

### ISSUE THREAD

**Issue by grabbe-bryghtlabs** [bhlangonijr/chesslib#113]
From this fenstring, moving c7c8 is not in the legal moves list.

R7/2P1N1k1/8/1p4pp/1P2p2P/4P3/5P2/6K1 w - - 1 2

Using version 1.3.3

**Comment by bhlangonijr** [comment]
Are you sure? I am getting the promotion and all the underpromotions there (**c7c8q, c7c8r, c7c8b, c7c8n**):

```
        Board board = new Board();
        board.loadFromFen("R7/2P1N1k1/8/1p4pp/1P2p2P/4P3/5P2/6K1 w - - 1 2");
        System.out.println(board.legalMoves());
```
this will print:
```
[h4g5, f2f3, f2f4, c7c8q, c7c8r, c7c8b, c7c8n, e7d5, e7f5, e7c6, e7g6, e7c8, e7g8, a8a1, a8a2, a8a3, a8a4, a8a5, a8a6, a8a7, a8b8, a8c8, a8d8, a8e8, a8f8, a8g8, a8h8, g1f1, g1h1, g1g2, g1h2]
```        
Mind that piece type is added to the long algebraic notation when converting to string. Is that what you are seeing too?
