### ISSUE TITLE
Illegal moves (the pawn can move backwards, a1 a3 from start etc )

### ISSUE THREAD

**Issue by evgentset** [bhlangonijr/chesslib#5]
First of all, many thanks for this library, it is very helpful.
During using it I found a bug, I suppose. Steps to reproduce are:
1. e2 e4
2. e7 e5 (or any other move)
3. e4 e2 

Expected result - "e4 e2" is illegal move for pawn. The Pawn can never move backwards. 
Actual result - board.doMove(move, true) returns true. 

I suppose that need to change something in method isMoveLegal(Move move, boolean fullValidation)  to make similar moves illegal.

**Comment by evgentset** [comment]
Also I found that there are a lot of similar illegal moves which  board.doMove(move, true) is allowed, like e1 e3 from start etc. So maybe I use it incorrect way? Because  MoveGenerator.generateLegalMoves(board) is generated all legal moves correctly. 
Could anybody explain what went wrong?

**Comment by bhlangonijr** [comment]
Hi @evgentset, yes I agree the name of the function `isMoveLegal` is misleading in regards to what it actually does. This library is a by-product of an UI development and for checking the legality of a move I actually call `MoveGenerator.generateLegalMoves(board)` and match the results against the move user is trying to play before executing `board.doMove(move)`. It means that you are free to use `board#doMove(move)` as long as the board is left in a valid state (e.g. side did not play a move leaving own king in check). You could use doMove() for moving pieces around to set up an arbitrary chessboard position using a drag & drop functionality in the UI, for example. Another useful usage is when you are fetching a move from a transposition table and replay it to `Board`: `board.doMove(move, true)` ensures the move is still valid for that given position. In that sense a more accurate name for this function would be `isBoardLegalFor(move)` or something like that.
I am open to suggestions though. Let me know what are your thoughts.

**Comment by evgentset** [comment]
ok, as you said, I've written util function to check it (koltin code, but java will be very similar):
```
fun isLegalMove(move: Move, board: Board): Boolean `{`
        val moveList = MoveGenerator.generateLegalMoves(board)
        return moveList.contains(move)
    }
```
So yes, it's just misleading for function name. You can mark these methods as deprecated in new library version, and copy them with another names. So users can easy migrate to another methods. I suppose it's acceptable solution for it.

Btw, I have not found function like 
` List<Move> getLegalMovesForPieceInSquare(Square square)`
which also may be very helpful as well. This method should get Piece in Square and return legal moves for the Piece in some Sqare.
I'm going to write similar function in future. If I have time I will send you pull request with it (I hope so). 

Many thanks again, 
Cheers
