### ISSUE TITLE
Typo on readme perft()

### ISSUE THREAD

**Issue by omarpalacios** [bhlangonijr/chesslib#57]
The line `List<Move> moves = board.legalModes();` should be: ... legalMo**v**es() I believe.

**Comment by bhlangonijr** [comment]
thank you @omarpalacios

**Comment by ZeroOne3010** [comment]
I have opened PR #59 that fixes this and other issues with the readme.

**Comment by bhlangonijr** [comment]
Fixed release 1.3.0
