### ISSUE TITLE
Feature - Count the number of games in a PGN file before loading it

### ISSUE THREAD

**Issue by liebig** [bhlangonijr/chesslib#63]
A function to count the number of games in a PGN file before loading would be interesting, as this would also allow a PgnLoadListener to calculate the exact percentage of games currently processed. I will create a pull request for this implementation.

**Comment by liebig** [comment]
For the implementation I count all lines which start with the string "[Event " because the Event field is mandatory by [PGN definition](http://www.saremba.de/chessgml/standards/pgn/pgn-complete.htm#c8). This implementation is fast. Counting 121332 games took my PC 707ms while loading the PGN file took 18597ms.

**Comment by bhlangonijr** [comment]
Hi @liebig would you do a PR for this one?
